using BManagedClient.BMsrv;
using System;
using System.ServiceModel;

namespace BManagedClient
{
    // =========================================================================
    // ServiceGateway + ClientSession — WPF infrastructure
    // -------------------------------------------------------------------------
    // ServiceGateway:
    //   Wraps every WCF call from WPF. Owns ONE shared Service1Client (a SOAP
    //   proxy generated by svcutil into Connected Services\BMsrv\Reference.cs)
    //   and exposes a Use() helper so callers can write business logic without
    //   thinking about WCF channel state.
    //   Architectural placement: WPF → ServiceGateway → Service1Client (proxy)
    //                            → BasicHttpBinding → port 8733 → Service1
    //                            → ViewDB → Access (.accdb).
    //
    // ClientSession:
    //   Static read-only view over LogIn.sign (the in-memory current user).
    //   Pages query ClientSession.IsOwner / IsEmployee / IsClient to drive
    //   role-based redirects and visibility — no need to read LogIn.sign
    //   directly from XAML/code-behind.
    // =========================================================================
    public static class ServiceGateway
    {
        // ---------------------------------------------------------------------
        // The shared WCF client. Replaced (Abort + re-new) only when the
        // channel transitions to Faulted / Closed. Pre-2026 we created a
        // brand-new Service1Client per Use() call which forced TCP handshake
        // + WCF Open() every single SOAP op — pages with 5–6 calls in a row
        // (Reports, Owner Home) burned hundreds of ms on plumbing alone.
        // ---------------------------------------------------------------------
        private static Service1Client _shared;
        // Mutex around _shared so two threads (e.g. login button + DispatcherTimer
        // poll) don't race to rebuild the client at the same time.
        private static readonly object _lock = new object();

        /// <summary>
        /// Lazy-cache accessor for the shared client. Called by every Use().
        /// Rebuilds the proxy if it is null or in a non-recoverable state
        /// (Faulted, Closed, Closing). Callers never new-up Service1Client.
        /// </summary>
        private static Service1Client GetClient()
        {
            lock (_lock)
            {
                // States we cannot recover from — the underlying channel is gone.
                if (_shared == null
                    || _shared.State == CommunicationState.Faulted
                    || _shared.State == CommunicationState.Closed
                    || _shared.State == CommunicationState.Closing)
                {
                    if (_shared != null)
                    { try { _shared.Abort(); } catch { } _shared = null; }
                    _shared = new Service1Client();
                }
                return _shared;
            }
        }

        /// <summary>
        /// Run a SOAP-using lambda on the shared channel and return its result.
        /// Catches any exception, aborts the channel, and rethrows so a faulted
        /// state does not silently persist into the next call.
        /// </summary>
        /// <typeparam name="T">Return type of the WCF op (e.g. User, bool, Invoice[]).</typeparam>
        /// <param name="action">Lambda that receives the proxy and calls one or more SOAP ops.</param>
        /// <example>
        /// var user = ServiceGateway.Use(c => c.GetUserById(c.GetUserId(name)));
        /// </example>
        public static T Use<T>(Func<Service1Client, T> action)
        {
            try { return action(GetClient()); }
            catch
            {
                // Force a rebuild on the next call so a transient channel fault
                // (server restart, network blip) doesn't break the whole app.
                lock (_lock)
                {
                    if (_shared != null) { try { _shared.Abort(); } catch { } }
                    _shared = null;
                }
                throw;
            }
        }

        /// <summary>
        /// Void overload — same as Use&lt;T&gt; but for SOAP ops that don't
        /// return anything (UpdateXxx, DeleteXxx, MarkXxx, etc.).
        /// </summary>
        public static void Use(Action<Service1Client> action)
        {
            Use(client => { action(client); return true; });
        }

        /// <summary>
        /// Pre-open the channel ahead of time so the first user-visible call
        /// doesn't pay the cold-start cost. Call once after a successful login
        /// to hide the WCF handshake latency from the user.
        /// </summary>
        public static void Warm()
        {
            try
            {
                var c = GetClient();
                if (c.State == CommunicationState.Created) c.Open();
            }
            catch { /* best-effort — if it fails, the next real call will retry. */ }
        }

        /// <summary>
        /// Force a fresh client on next Use(). Useful when the user changes the
        /// WCF endpoint (env-var override) or after a server restart.
        /// </summary>
        public static void Reset()
        {
            lock (_lock)
            {
                if (_shared != null) { try { _shared.Abort(); } catch { } }
                _shared = null;
            }
        }
    }

    /// <summary>
    /// Static read-only facade over <see cref="LogIn.sign"/> — the in-memory
    /// user record set on successful authentication. Pages and converters
    /// query this instead of touching <c>LogIn.sign</c> directly so role logic
    /// is centralised. Roles in B-Managed: Owner, Employee, Client.
    /// </summary>
    public static class ClientSession
    {
        /// <summary>Currently signed-in user's id; -1 when no session.</summary>
        public static int CurrentUserId => LogIn.sign?.Id ?? -1;
        /// <summary>Currently signed-in user's role string; empty when no session.</summary>
        public static string Role => LogIn.sign?.Role ?? "";
        /// <summary>True for full-admin Owner accounts.</summary>
        public static bool IsOwner    => Role == "Owner";
        /// <summary>True for Employee accounts (assigned to one Owner via Users.OwnerId).</summary>
        public static bool IsEmployee => Role == "Employee";
        /// <summary>True for Client (customer-portal) accounts.</summary>
        public static bool IsClient   => Role == "Client";
        /// <summary>Combines id + role check — the canonical "is anyone signed in?".</summary>
        public static bool IsLoggedIn => CurrentUserId > 0 && !string.IsNullOrEmpty(Role);
    }
}
